# -*- coding: utf-8 -*-
"""AI_Resume_Ranker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109n1FXMznmE3wCyBgl-gmrN4pksrDrx5
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Replace this with a appropriate job description
job_description = """
We are looking for a Junior AI Engineer with experience in Python,
Machine Learning, and Data Visualization. Knowledge of Scikit-learn
and API integration is a must. Communication skills are highly valued.
"""

# Replace these with appropriate resume and a "fake" bad resume for comparison
resume_1 = "BSc Graduate in Computer Science. Proficient in Python, Machine Learning, and Scikit-learn. Built several data visualization projects."
resume_2 = "Experienced Chef with 10 years in Italian cuisine. Expert in pasta, kitchen management, and team leadership."

content = [job_description, resume_1, resume_2]

cv = CountVectorizer()
matrix = cv.fit_transform(content)

similarity_matrix = cosine_similarity(matrix)

# Match scores compared to the Job Description
score_1 = similarity_matrix[0][1] * 100
score_2 = similarity_matrix[0][2] * 100

print(f"Resume 1 Match Score: {score_1:.2f}%")
print(f"Resume 2 Match Score: {score_2:.2f}%")

import ipywidgets as widgets
from IPython.display import display

# Create the UI elements
jd_input = widgets.Textarea(placeholder='Paste Job Description here', description='JD:', layout={'height': '100px', 'width': '80%'})
cv_input = widgets.Textarea(placeholder='Paste Resume here', description='Resume:', layout={'height': '100px', 'width': '80%'})
button = widgets.Button(description="Calculate Match", button_style='success')
output = widgets.Output()

def on_button_clicked(b):
    with output:
        output.clear_output()
        text_list = [jd_input.value, cv_input.value]
        cv = CountVectorizer()
        matrix = cv.fit_transform(text_list)
        score = cosine_similarity(matrix)[0][1] * 100
        print(f"--- RESULT ---\nMatch Accuracy: {score:.2f}%")

button.on_click(on_button_clicked)
display(jd_input, cv_input, button, output)